# Generated by Django 4.2.7 on 2023-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_1',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='post',
            name='description_2',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='post',
            name='title_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title_2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
