# Generated by Django 4.2.7 on 2023-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description_1_post_description_2_post_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
