# Generated by Django 4.2.7 on 2023-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_description_1_alter_post_description_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_1',
            field=models.TextField(default=''),
        ),
    ]
