# Generated by Django 4.2.7 on 2023-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url2',
            field=models.URLField(blank=True),
        ),
    ]
